### ISSUE TITLE
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.

### ISSUE THREAD

**Issue by cstrat** [meteorhacks/kadira-binary-deps#5]
```
meteor build ../_builds/  --architecture os.linux.x86_64

=> Errors while initializing project:

While checking for meteorhacks:kadira-binary-deps@1.5.0:
error: No compatible binary build found for this package. Contact the package author and ask them to publish it for your platform.
```

I ran `meteor update` and am now getting this error when trying to build.
Should I downgrade my kadira, or is this something that can get updated quickly?

**Comment by louis49** [comment]
+1

**Comment by lynchem** [comment]
Same here after updating to Meteor 1.3.5.1 . Have reverted for now.

**Comment by cstrat** [comment]
It seems this has been fixed now.
I ran `meteor update` and with 1.3.5.1 the new binary downloaded and my project was built and packaged just fine.

**Comment by igeto** [comment]
Hi, I am trying to update a meteor poject from 1.4.3 to 1.6.0.1 and I am getting this error
Does anyone have a fix?
